os:
    - linux
    - osx
    - windows

language: node_js

node_js:
    - '4.4.7'
    
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++-4.9-dev
            - gcc-4.9
            - g++-4.9
            - xvfb

before_install:
    - export CC="gcc-4.9"
    - export CXX="g++-4.9"

install:
    - npm install

before_script:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
    - sleep 3 # give xvfb some time to start
    - ps -a

branches:
    only:
        - travis