os:
    - linux
    - osx
    - windows

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libstdc++-4.9-dev
            - xvfb

install:
    - export DISPLAY=':99.0'
    - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

language: node_js

node_js:
    - '4.4.7'

branches:
    only:
        - travis